#!/bin/bash

TRUVARI_RESULTS=$1

#Build Truvari Subfolders
echo "Building Truvari result set subdirectories!.."
#Pair Combos
mkdir $TRUVARI_RESULTS/PAV-SVIM 
mkdir $TRUVARI_RESULTS/CuteSV-PAV
mkdir $TRUVARI_RESULTS/PAV-Sniffles
mkdir $TRUVARI_RESULTS/PAV-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-SVIM
mkdir $TRUVARI_RESULTS/Sniffles-SVIM
mkdir $TRUVARI_RESULTS/SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-ASM
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-ASM

#Trip Combos
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM/INV

mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM/ALL
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM/DEL
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM/INS
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM/INV

mkdir $TRUVARI_RESULTS/PAV-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/PAV-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/PAV-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/PAV-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/PAV-SVIM-SVIM-ASM/INV

mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles/INV

mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-ASM/INV

mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-ASM
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-ASM/INV

mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/INS
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/DUP
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/INV
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM/BND

mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM/DUP
mkdir $TRUVARI_RESULTS/CuteSV-SVIM-SVIM-ASM/BND

mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM/DUP
mkdir $TRUVARI_RESULTS/Sniffles-SVIM-SVIM-ASM/BND

mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM/DUP
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-ASM/BND

#Quad Combos
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/ALL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/ALL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/DEL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/DEL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INS/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INS/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INV
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INV/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM/INV/Base

mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/ALL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/ALL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/DEL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/DEL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INS/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INS/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INV
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INV/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-SVIM-SVIM-ASM/INV/Base

mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/ALL/Call
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/ALL/Base
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/DEL/Call
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/DEL/Base
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INS/Call
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INS/Base
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INV
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INV/Call
mkdir $TRUVARI_RESULTS/PAV-Sniffles-SVIM-SVIM-ASM/INV/Base

mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/ALL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/ALL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/DEL/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/DEL/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INS/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INS/Base
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INV
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INV/Call
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-ASM/INV/Base

mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/ALL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/ALL/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/ALL/Base
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DEL
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DEL/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DEL/Base
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INS
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INS/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INS/Base
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DUP
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DUP/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/DUP/Base
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INV
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INV/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/INV/Base
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/BND
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/BND/Call
mkdir $TRUVARI_RESULTS/CuteSV-Sniffles-SVIM-SVIM-ASM/BND/Base

#Five Combo
mkdir $TRUVARI_RESULTS/CuteSV-PAV-Sniffles-SVIM-SVIM-ASM

echo "Work complete!.."
